    module ModNeighbor
        use ModMesh
        use ModTypDef 
        use ModInpMesh
        implicit none
    contains
    
! X- neighbor 
    recursive function NeighborX1(c) RESULT(Neighbor)
        implicit none
        type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor
        !cf,c'father;cinitial,c'initial X- neighbor;cfn,c'father's X- neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(1)==1)then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1)-1,c%nBGCell(2),c%nBGCell(3))
            endif
            return
        endif
        
        cfn=>NeighborX1(cf)
        if(associated(cfn))then
            if(c%fSplitType==0)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0 .or. &
                           cfn%son1%fSplitType==1 .or. &
                           cfn%son1%fSplitType==4 .or. &
                           cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son2
                        else !cfn%son1%fSplitType==2  3  6
                            Neighbor=>cfn%son1   
                        endif
                    endif
                elseif(c%Location==2)then
                    Neighbor=>cf%son1
                elseif(c%Location==3)then
                    Neighbor=>cf%son4
                elseif(c%Location==4)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son3
                        elseif(cfn%son1%fSplitType==3)then                         
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn%son2                !cfn%son1%fSplitType==1  2  5  6
                        endif
                    endif
                elseif(c%Location==5)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son6
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==2)then      
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==5)then      
                            Neighbor=>cfn%son3
                        else      
                            Neighbor=>cfn%son4                      
                        endif
                    endif
                elseif(c%Location==6)then
                    Neighbor=>cf%son5
                elseif(c%Location==7)then
                    Neighbor=>cf%son8
                elseif(c%Location==8)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son7
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        else                         !cfn%son1%fSplitType==4  5  6
                            Neighbor=>cfn%son3                      
                        endif
                    endif
                endif
            elseif(c%fSplitType==1)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then
                            Neighbor=>cfn%son2
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    Neighbor=>cf%son1
                endif
            elseif(c%fSplitType==2)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==4)then
                             Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==2)then
                             Neighbor=>cfn%son1
                        else
                             Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==2)then
                             Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4)then
                             Neighbor=>cfn%son3
                        else
                             Neighbor=>cfn
                        endif
                    endif
                endif
            elseif(c%fSplitType==3)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son3
                        else
                            Neighbor=>cfn
                        endif
                    endif
                endif
            elseif(c%fSplitType==4)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==2)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    Neighbor=>cf%son1
                elseif(c%Location==3)then
                    Neighbor=>cf%son4
                elseif(c%Location==4)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==2)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son3
                        else
                            Neighbor=>cfn
                        endif
                    endif
                endif
            elseif(c%fSplitType==5)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    Neighbor=>cf%son1
                elseif(c%Location==3)then
                    Neighbor=>cf%son4
                elseif(c%Location==4)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son3
                        else
                            Neighbor=>cfn
                        endif
                    endif
                endif
            elseif(c%fSplitType==6)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn%son2                !cfn%son1%fSplitType==0  1  4  5  
                        endif
                    endif
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son3
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son1
                        else                              !cfn%son1%fSplitType==1  2  5  6
                            Neighbor=>cfn%son2               
                        endif
                    endif
                elseif(c%Location==3)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son7
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4.or.&
                            cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then     
                            Neighbor=>cfn%son3               
                        endif
                    endif
                elseif(c%Location==4)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son6
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==2)then     
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==5)then     
                            Neighbor=>cfn%son3 
                        elseif(cfn%son1%fSplitType==6)then     
                            Neighbor=>cfn%son4     
                        endif
                    endif
                endif
            endif
        endif
        return
    end function NeighborX1
    
! X+ neighbor 
    recursive function NeighborX2(c) RESULT(Neighbor)
        implicit none
        type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor
        !cf,c'father;cinitial,c'initial X+ neighbor;cfn,c'father's X+ neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(1)==nCell(1))then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1)+1,c%nBGCell(2),c%nBGCell(3))
            endif
            return
        endif
        
        cfn=>NeighborX2(cf)
        if(associated(cfn))then
            if(c%fSplitType==0)then
                if(c%Location==1)then
                    Neighbor=>cf%son2
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        Neighbor=>cfn%son1
                    endif
                elseif(c%Location==3)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son4
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son2
                        endif
                    endif
                elseif(c%Location==4)then
                    Neighbor=>cf%son3
                elseif(c%Location==5)then    
                    Neighbor=>cf%son6
                elseif(c%Location==6)then  
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son5
                        elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son4
                        endif
                    endif
                elseif(c%Location==7)then    
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son8
                        elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son4
                        elseif(cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son3    
                        endif
                    endif
                elseif(c%Location==8)then
                    Neighbor=>cf%son7
                endif                           
            elseif(c%fSplitType==1)then
                if(c%Location==1)then
                    Neighbor=>cf%son2
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif           
                    endif
                endif 
            elseif(c%fSplitType==2)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif        
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==2)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son4
                        elseif(cfn%son1%fSplitType==1)then
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif     
                endif 
            elseif(c%fSplitType==3)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then ! ==1 need to be noticed
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then ! ==1 need to be noticed
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son4
                        else
                            Neighbor=>cfn
                        endif
                    endif
                endif 
            elseif(c%fSplitType==4)then
                if(c%Location==1)then
                    Neighbor=>cf%son2
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then 
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==3)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then 
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==2)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son4
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==4)then    
                    Neighbor=>cf%son3 
                endif 
            elseif(c%fSplitType==5)then
                if(c%Location==1)then
                    Neighbor=>cf%son2 
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then 
                            Neighbor=>cfn%son1
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==3)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==1)then 
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son4
                        else
                            Neighbor=>cfn
                        endif
                    endif
                elseif(c%Location==4)then    
                    Neighbor=>cf%son3
                endif 
            elseif(c%fSplitType==6)then
                if(c%Location==1)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        Neighbor=>cfn%son1                    !may be bug   
                    endif
                elseif(c%Location==2)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son4
                        else
                            Neighbor=>cfn%son1
                        endif                                        
                    endif
                elseif(c%Location==3)then
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son8
                        elseif(cfn%son1%fSplitType==1)then
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then
                            Neighbor=>cfn%son4 
                        elseif(cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son3
                        endif                                        
                    endif
                elseif(c%Location==4)then    
                    if(.not.associated(cfn%son1))then
                        Neighbor=>cfn
                    elseif(associated(cfn%son1))then
                        if(cfn%son1%fSplitType==0)then
                            Neighbor=>cfn%son5
                        elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then
                            Neighbor=>cfn%son1
                        elseif(cfn%son1%fSplitType==3)then
                            Neighbor=>cfn%son2
                        elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                            Neighbor=>cfn%son4 
                        endif                                        
                    endif
                endif 
            endif
        endif
        return
    end function NeighborX2   
    
! Y- neighbor
    recursive function NeighborY1(c) RESULT(Neighbor)
        implicit none
            type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor 
            !cf,c'father;cinitial,c'initial Y- neighbor;cfn,c'father's Y- neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(2)==1)then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1),c%nBGCell(2)-1,c%nBGCell(3))
            endif
            return
        endif
        
            cfn=>NeighborY1(cf)
            if(associated(cfn))then
                if(c%fSplitType==0)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            endif
                        endif
                    elseif(c%Location==3)then
                        Neighbor=>cf%son2
                    elseif(c%Location==4)then
                        Neighbor=>cf%son1
                    elseif(c%Location==5)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son8
                            elseif(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3    
                            endif
                        endif
                    elseif(c%Location==6)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son7
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4.or.&
                            cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3
                            endif
                        endif
                    elseif(c%Location==7)then
                        Neighbor=>cf%son6
                    elseif(c%Location==8)then
                        Neighbor=>cf%son5
                    endif
                elseif(c%fSplitType==1)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2    
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3    
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==2)then 
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        Neighbor=>cf%son1
                    endif
                elseif(c%fSplitType==3)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==4)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2    
                            elseif(cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==3)then
                        Neighbor=>cf%son2
                    elseif(c%Location==4)then
                        Neighbor=>cf%son1
                    endif
                elseif(c%fSplitType==5)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else                         !  1  2  5  6
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son7
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4.or.&
                            cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son3
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son8
                            elseif(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then         
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son3
                            endif
                        endif
                    endif
                elseif(c%fSplitType==6)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else         
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        Neighbor=>cf%son1
                    elseif(c%Location==3)then
                        Neighbor=>cf%son4
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son3
                            else         
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                endif
            endif
            return
    end function NeighborY1
    
! Y+ neighbor
    recursive function NeighborY2(c) RESULT(Neighbor)
        implicit none
            type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor 
            !cf,c'father;cinitial,c'initial Y+ neighbor;cfn,c'father's Y+ neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(2)==nCell(2))then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1),c%nBGCell(2)+1,c%nBGCell(3))
            endif
            return
        endif
        
            cfn=>NeighborY2(cf)
            if(associated(cfn))then
                if(c%fSplitType==0)then
                    if(c%Location==1)then
                        Neighbor=>cf%son4
                    elseif(c%Location==2)then
                        Neighbor=>cf%son3
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son1
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            Neighbor=>cfn%son1
                        endif
                    elseif(c%Location==5)then
                        Neighbor=>cf%son8
                    elseif(c%Location==6)then
                        Neighbor=>cf%son7
                    elseif(c%Location==7)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son6
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then         
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==5)then         
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son4
                            endif
                        endif
                    elseif(c%Location==8)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son5
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son4
                            endif
                        endif
                    endif
                elseif(c%fSplitType==1)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son1
                            else         
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then         
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==2)then 
                    if(c%Location==1)then
                        Neighbor=>cf%son2
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then         
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==3)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then         
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==4)then
                    if(c%Location==1)then
                        Neighbor=>cf%son4
                    elseif(c%Location==2)then
                        Neighbor=>cf%son3
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then         
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then         
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==5)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            Neighbor=>cfn%son1
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then         
                                Neighbor=>cfn%son2
                            else      
                                Neighbor=>cfn%son1
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then         
                                Neighbor=>cfn%son6
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then       
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then       
                                Neighbor=>cfn%son1 
                            elseif(cfn%son1%fSplitType==5)then       
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==6)then       
                                Neighbor=>cfn%son4
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then         
                                Neighbor=>cfn%son5
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then       
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then       
                                Neighbor=>cfn%son2 
                            elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then       
                                Neighbor=>cfn%son4
                            endif
                        endif
                    endif
                elseif(c%fSplitType==6)then
                    if(c%Location==1)then
                        Neighbor=>cf%son2
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then           
                                Neighbor=>cfn%son1
                            else       
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then           
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then           
                                Neighbor=>cfn%son2 
                            elseif(cfn%son1%fSplitType==6)then           
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==4)then
                        Neighbor=>cf%son3
                    endif
                endif
            endif
            return
    end function NeighborY2    
 
! Z- neighbor
    recursive function NeighborZ1(c) RESULT(Neighbor)
        implicit none
            type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor 
            !cf,c'father;cinitial,c'initial Z- neighbor;cfn,c'father's Z- neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(3)==1)then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1),c%nBGCell(2),c%nBGCell(3)-1)
            endif
            return
        endif
        
            cfn=>NeighborZ1(cf)
            if(associated(cfn))then
                if(c%fSplitType==0)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son5
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son6
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4   
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son7
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            else                        !4   5   6
                                Neighbor=>cfn%son3   
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son8
                            elseif(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3  
                            endif
                        endif
                    elseif(c%Location==5)then
                        Neighbor=>cf%son1  
                    elseif(c%Location==6)then
                        Neighbor=>cf%son2  
                    elseif(c%Location==7)then
                        Neighbor=>cf%son3  
                    elseif(c%Location==8)then
                        Neighbor=>cf%son4  
                    endif
                elseif(c%fSplitType==1)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn  
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son3
                            else
                                Neighbor=>cfn  
                            endif
                        endif
                    endif
                elseif(c%fSplitType==2)then 
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4
                            else    
                                Neighbor=>cfn  
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3
                            else    
                                Neighbor=>cfn  
                            endif
                        endif
                    endif
                elseif(c%fSplitType==3)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            else
                                Neighbor=>cfn  
                            endif
                        endif
                    elseif(c%Location==2)then
                        Neighbor=>cf%son1
                    endif
                elseif(c%fSplitType==4)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son5
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2 
                            elseif(cfn%son1%fSplitType==5.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son6
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son1 
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son7
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            else
                                Neighbor=>cfn%son3
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0)then
                                Neighbor=>cfn%son8
                            elseif(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2 
                            elseif(cfn%son1%fSplitType==4.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3
                            endif
                        endif
                    endif
                elseif(c%fSplitType==5)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2 
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son3
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==3)then
                        Neighbor=>cf%son2
                    elseif(c%Location==4)then
                        Neighbor=>cf%son1
                    endif
                elseif(c%fSplitType==6)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2)then
                                Neighbor=>cfn%son1
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son4
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son3
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==3)then
                        Neighbor=>cf%son2
                    elseif(c%Location==4)then
                        Neighbor=>cf%son1
                    endif
                endif
            endif
            return
    end function NeighborZ1        

! Z+ neighbor
    recursive function NeighborZ2(c) RESULT(Neighbor)
        implicit none
            type(OctCell),pointer :: c,cf,cinitial,cfn,Neighbor 
            !cf,c'father;cinitial,c'initial Z+ neighbor;cfn,c'father's Z+ neighbor
        
        Neighbor=>null()
        cf=>c%father
        
        if(.not.associated(cf))then
            if(c%nBGCell(3)==nCell(3))then
                Neighbor=>null()
            else
                Neighbor=>Cell(c%nBGCell(1),c%nBGCell(2),c%nBGCell(3)+1)
            endif
            return
        endif
        
            cfn=>NeighborZ2(cf)
            if(associated(cfn))then
                if(c%fSplitType==0)then
                    if(c%Location==1)then
                        Neighbor=>cf%son5
                    elseif(c%Location==2)then
                        Neighbor=>cf%son6
                    elseif(c%Location==3)then
                        Neighbor=>cf%son7
                    elseif(c%Location==4)then
                        Neighbor=>cf%son8
                    elseif(c%Location==5)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            Neighbor=>cfn%son1
                        endif
                    elseif(c%Location==6)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==7)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==8)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn%son2
                            endif
                        endif
                    endif
                elseif(c%fSplitType==1)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==2)then 
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==3)then
                    if(c%Location==1)then
                        Neighbor=>cf%son2
                    elseif(c%Location==2)then
                        Neighbor=>cfn
                    endif
                elseif(c%fSplitType==4)then
                    if(c%Location==1)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            Neighbor=>cfn%son1
                        endif
                    elseif(c%Location==2)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son3
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn%son2
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==0.or.cfn%son1%fSplitType==4)then
                                Neighbor=>cfn%son4
                            elseif(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            else
                                Neighbor=>cfn%son1
                            endif
                        endif
                    endif
                elseif(c%fSplitType==5)then
                    if(c%Location==1)then
                        Neighbor=>cf%son4
                    elseif(c%Location==2)then
                        Neighbor=>cf%son3
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==1.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==5)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn
                            endif
                        endif
                    endif
                elseif(c%fSplitType==6)then
                    if(c%Location==1)then
                        Neighbor=>cf%son4
                    elseif(c%Location==2)then
                        Neighbor=>cf%son3
                    elseif(c%Location==3)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son2
                            elseif(cfn%son1%fSplitType==3)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn   
                            endif
                        endif
                    elseif(c%Location==4)then
                        if(.not.associated(cfn%son1))then
                            Neighbor=>cfn
                        elseif(associated(cfn%son1))then
                            if(cfn%son1%fSplitType==2.or.&
                            cfn%son1%fSplitType==3.or.cfn%son1%fSplitType==6)then
                                Neighbor=>cfn%son1
                            else
                                Neighbor=>cfn   
                            endif
                        endif
                    endif
                endif
            endif
            return
    end function NeighborZ2        

    end module ModNeighbor
    
    